server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: catalog-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/catalog_db}
    username: ${SPRING_DATASOURCE_USERNAME:catalog_service}
    password: ${SPRING_DATASOURCE_PASSWORD:catalog_service}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:inventory-secret-key-insecure-change-me-2026}
    access-token-minutes: ${SECURITY_JWT_ACCESS_TOKEN_MINUTES:240}
    issuer: ${SECURITY_JWT_ISSUER:inventory-platform}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

clients:
  inventory:
    url: ${CLIENTS_INVENTORY_URL:http://inventory-service:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info
