server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${SERVICES_USER_URI:lb://user-service}
          predicates:
            - Path=/api/auth/**,/api/users/**
        - id: catalog-service
          uri: ${SERVICES_CATALOG_URI:lb://catalog-service}
          predicates:
            - Path=/api/categories/**,/api/products/**
        - id: inventory-service
          uri: ${SERVICES_INVENTORY_URI:lb://inventory-service}
          predicates:
            - Path=/api/movements/**,/api/stocks/**
        - id: report-service
          uri: ${SERVICES_REPORT_URI:lb://report-service}
          predicates:
            - Path=/api/reports/**

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
