server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/user_db}
    username: ${SPRING_DATASOURCE_USERNAME:user_service}
    password: ${SPRING_DATASOURCE_PASSWORD:user_service}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:inventory-secret-key-insecure-change-me-2026}
    access-token-minutes: ${SECURITY_JWT_ACCESS_TOKEN_MINUTES:240}
    issuer: ${SECURITY_JWT_ISSUER:inventory-platform}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info
