SPRING_PROFILES_ACTIVE: cloud
EUREKA_CLIENT_ENABLED: "false"
SERVICES_USER_URI: https://user-service-xxxxx-uc.a.run.app
SERVICES_CATALOG_URI: https://catalog-service-xxxxx-uc.a.run.app
SERVICES_INVENTORY_URI: https://inventory-service-xxxxx-uc.a.run.app
SERVICES_REPORT_URI: https://report-service-xxxxx-uc.a.run.app
